apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi

    spec:
      containers:
        - name: fastapi
          image: devops-demo-app:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: fastapi-config
